---
title: "Untitled"
output:
  pdf_document:
    fig_caption: yes
    number_sections: no
    keep_tex: true
    pandoc_args:

csl: evolution.csl
bibliography: Pristurus-Refs.bib

header-includes:
    - \usepackage{setspace}\doublespacing
    - \usepackage{lineno}\linenumbers
fontsize: 11pt
---

Elucidating the selective forces that generate patterns of phenotypic diversity is a major goal in evolutionary biology. For species that utilize distinct habitats, disentangling the causes of phenotypic differentiation is essential for our understanding of how natural selection operates and how evolution proceeds. In this study, we evaluated the role of potential drivers of body shape differentiation in the geckos of the genus *Pristurus*. To this end, we compared allometric trends and levels of integration among *Pristurus* occopying distinct habitats, interrogated allometric patterns at both the static and evolutionary levels, and related these trends to diversification in body form. Our findings have several important implications for how ecological specialization, phenotypic integration, and body form evolution along allometric trajectories relate to patterns of phenotypic diversity generally, and the evolution of phenotypic diversification in *Pristurus* in particular. \hfill\break

First, our analyzes revealed that patterns of body shape allometry and morphological integration are relatively distinct in ground-dwelling *Pristurus* lizards, as compared with *Pristurus* occupying other habitats. Specifically, we found that multivariate vectors of regression coefficients differed significantly from what was expected under isometry (Table 2) for taxa utilizing all habitat types (ground, rock, tree), indicating that in *Pristurus*, allometric patterns predominate. Further, our interrogation of allometric trends revealed differences between habitat types, where ground-dwelling *Pristurus* displayed steeper (i.e., positively allometric) trends for both head and limb traits, while rock and tree-dwelling taxa displayed shallower (negatively allometric) trends for head traits and more varied patterns for limb proportions. Biologically, these patterns revealed that not only does shape differ between large and small *Pristurus*, but this pattern differs across habitat types. Specifically, large ground-dwelling *Pristurus* present disproportionately larger heads and longer limbs relative to large individuals in other habitats, while small ground-dwelling *Pristurus* exhibit disproportionately smaller heads and shorter limbs (Figure 3). These findings are consistent with previous work at the macroevolutionary level, [@Tejero-Cicuendez2021], where large ground species were also found to display disproportionately large heads and long limbs. \hfill\break

Second, our findings revealed that in rock-dwelling *Pristurus* a converse pattern was found, where smaller individuals displayed relatively larger heads, while larger individuals proportionately smaller heads for their body size. These allometric patterns are also corresponded with findings at macroevolutioanry scales [@Tejero-Cicuendez2021], where similar patterns at the species level were observed. Additionally, analyses by Tejero-Cicu\'{e}ndez et al. [-@Tejero-Cicuendez2021] indicated that the rock habitat was the most likely ancestral condition in the group, with subsequent colonization of ground habitats. If this hypothesis is correct, it implies a concomitant evolutionary shift in allometric trajectories [sensu @AdamsNistri2010] from a more rock-like pattern to that found in ground-dwelling taxa, which our analyses reveal (Figure 3). This further suggests that the segregation in body size and shape through differential allometric relationships across habitats responds to adaptive dynamics concerning the colonization of new habitats. Thus, in *Pristurus*, there is support for the hypothesis that colonization of ground habitats has been a trigger for morphological change [@Tejero-Cicuendez2021], as there appears to be a link between shifts in allometric trajectories as a result of habitat-induced selection, and differential patterns of body shape observed across taxa. 

**NOTE: one thing I am not sure about is WHY we see **


Second, ....

Indeed, .... 

Additionally, ...

Finally, ....